### ISSUE TITLE
Proximity Sensor (PS) not activated correctly

### ISSUE THREAD

**Issue by thomasphillipsgb** [iohe/ltr-559#1]
### Issue
Invoking `Ltr559::set_ps_contr` doesn't actually enable the PS sensor.

### Expected behaviour
Invoke the `set_ps_contr`, then subsequently calling `get_ps_data` should give us back data.

### Actual behaviour
Invoke the `set_ps_contr`, then subsequently calling `get_ps_data` does not give us back data.

### Investigation
Having a read through source and comparing with the Ltr559 spec, seems we're supplying the incorrect value to the `PS_CONTR` register; we're sending 0x04 instead of 0x03.

Line - https://github.com/iohe/ltr-559/blob/c89165710b6cae25be3768aaa6d325001e0094e5/src/device_impl.rs#L135
Spec ref. - page 14/40 https://optoelectronics.liteon.com/upload/download/DS86-2013-0003/LTR-559ALS-01_DS_V1.pdf

**Comment by thomasphillipsgb** [comment]
I've addressed this locally, looking to add a small test. Would you be happy for me to raise a PR?

_Footnote; thanks @iohe for this crate, it's gotten me into rust development!_

**Comment by iohe** [comment]
merged proposed pr.
